insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (1, 'SUPER ORIGIN COTTON FINISH FOUNDATION', 'Unsp trochan fx unsp femr, 7thM', 'Bolian');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (2, 'Prometh with Codeine', 'Laceration of other part of colon, subsequent encounter', 'Lýkeio');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (3, 'Sulindac', 'Toxic effect of other metals, undetermined, init encntr', 'Aţ Ţawāḩīn');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (4, 'Tussin Original', 'Female genital prolapse', 'Changsheng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (5, 'MINERAL FOUNDATION', 'Nondisp fx of prox phalanx of l little fngr, init for opn fx', 'Dodu Dua');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (6, 'leader cold head congestion', 'Intentional self-harm by crashing of aircraft, sequela', 'Suizhou');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (7, 'Nutricel Additive Solution - CP2D', 'Sltr-haris Type III physeal fx upper end of r tibia, sequela', 'Dunkerque');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (8, 'Rabbitbush Pollen', 'Unspecified open wound, right thigh, sequela', 'Coutada');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (9, 'Flecainide Acetate', 'Secondary osteoarthritis of other joints', 'Klagen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (10, 'dg health ibuprofen', 'Pregnancy related peripheral neuritis, third trimester', 'Fonte Boa da Brincosa');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (11, 'Melafadin Day Protection', 'Oth fx upr & low end l fibula, 7thH', 'Rio Claro');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (12, 'Kroger', 'Disp fx of med condyle of unsp humer, subs for fx w nonunion', 'Tengqiao');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (13, 'ibuprofen', 'Anuria and oliguria', 'Long’an Chengxiangzhen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (14, 'VECURONIUM BROMIDE', 'Other reactive arthropathies, unspecified site', 'Duyun');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (15, 'Ramipril', 'Adverse effect of antiepileptic and sed-hypntc drugs, init', 'Bayt Qād');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (16, 'Banzel', 'Postdysenteric arthropathy, left shoulder', 'Kazanlŭk');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (17, 'sunmark', 'Unsp fx shaft of unsp ulna, 7thJ', 'Kŭrdzhali');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (18, 'Hydrocortisone Valerate', 'Nondisplaced Rolando''s fracture, unspecified hand, sequela', 'Sabi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (19, 'Disney Antibacterial Hand Wipes - TOY STORY, CARS, MONSTERS UNIVERSITY', 'Fracture of unspecified part of neck of left femur, sequela', 'Estacion');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (20, 'Burn Mist', 'Adverse effect of other synthetic narcotics, init encntr', 'Yesan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (21, 'Cetirizine Hydrochloride', 'Pressure ulcer of right lower back, stage 4', 'Soriano');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (22, 'LISINOPRIL AND HYDROCHLOROTHIAZIDE', 'Displ transverse fx shaft of humer, l arm, 7thG', 'Baiyangwan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (23, 'SIMPLY RIGHT', 'Dislocation of T11/T12 thoracic vertebra', 'Chambray-lès-Tours');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (24, 'Chlorhexidine Gluconate', 'Symblepharon', 'Sarmīn');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (25, 'Velivet', 'Milt op involving explosion of aerial bomb, civilian, init', 'Salzburg');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (26, 'Phoma glomerata', 'Unsp injury of extn musc/fasc/tend at forearm level', 'Fleury-les-Aubrais');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (27, 'Pistachio', 'Dermatochalasis of right upper eyelid', 'Hongmen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (28, 'Verapamil', 'Insect bite (nonvenomous), left lower leg, subs encntr', 'Ciyu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (29, 'Reserpine', 'Other cyst of bone, ankle and foot', 'Fort Liberté');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (30, 'hydrochlorothiazide', 'Pneumococcal arthritis, left knee', 'Winter Haven');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (31, 'Phenazopyridine Hydrochloride', 'Post disp fx of sternal end r clavicle, 7thG', 'Moutnice');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (32, 'Niacor', 'Unsp opn wnd abd wall, right lower q w penet perit cav, sqla', 'Lameiro');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (33, 'PHOSLYRA', 'Laceration of msl/tnd of front wall of thorax, subs', 'Helsingborg');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (34, 'Metoprolol Tartrate', 'Poisoning by angiotens-convert-enzyme inhibitors, acc, subs', 'Vale Maceiras');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (35, 'Lescol', 'Unspecified open wound of lower leg', 'Perepravnaya');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (36, 'Olanzapine', 'Alport syndrome', 'Molave');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (37, 'Antiseptic Mouth Rinse', 'Monoplegia of upper limb', 'Jetak Kulon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (38, 'Gabapentin', 'Ped on sktbrd injured in clsn w nonmtr vehicle nontraf, init', 'Timurjaya');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (39, 'Clonazepam', 'Hemorrhage of unspecified orbit', 'Ayorou');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (40, 'Homeopathic Remedy Kit 30c', 'Arthropathy following intestinal bypass, left hand', 'Lop Buri');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (41, 'FIBERCON', 'Encounter for other contraceptive management', 'Changting');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (42, 'Quintessence Q-Sunshade Leave In Hair Conditioner and Scalp Protectant SPF 30', 'Resistance to antifungal drug(s)', 'Kuidou');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (43, 'Multitrace -4 Pediatric', 'Nondisp seg fx shaft of unsp femur, init for opn fx type I/2', 'Baihe');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (44, 'Lyrica', 'Unspecified open wound of unspecified ear, sequela', 'Vista Hermosa');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (45, 'Tramadol Hydrochloride and Acetaminophen', 'Foreign body granuloma of soft tissue, NEC, ankle and foot', 'Khosta');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (46, 'PPH', 'STEMI involving oth coronary artery of anterior wall', 'Néa Éfesos');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (47, 'Mineral Oil, Petrolatum and Phenylephrine HCl', 'Medial disloc of proximal end of tibia, right knee, sequela', 'Shatki');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (48, 'Thyme', 'Glaucoma secondary to eye trauma, unsp eye, moderate stage', 'Sembon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (49, 'Leucovorin Calcium', 'Transient retinal artery occlusion', 'Yichun');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (50, 'Clonidine Hydrochloride', 'Disp fx of proximal phalanx of right lesser toe(s), sequela', 'Newmarket');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (51, 'Concealing Spot Treatment', 'Striking against wall of swimming pool causing drown, init', 'Vacoas');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (52, 'Clobetasol Propionate', 'Burn 2nd deg mul sites of right lower limb, ex ank/ft, subs', 'Otaslavice');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (53, 'Fetzima', 'Chronic myringitis, right ear', 'Bayan-Ovoo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (54, 'Amlodipine Besylate', 'Unspecified injury of body of pancreas, sequela', 'Alta');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (55, 'PLANTAGO LANCEOLATA POLLEN', 'Abrasion of lip and oral cavity', 'Malitubog');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (56, 'Moist SURE', 'Penetrating wound of orbit w or w/o foreign body, right eye', 'Campaka');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (57, 'Ceftriaxone Sodium', 'Smith''s fracture of r radius, subs for clos fx w malunion', 'Falun');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (58, 'Naproxen', 'Type III occipital condyle fracture, left side', 'Zhatay');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (59, 'Minocycline hydrochloride', 'Unspecified superficial injury of right ankle, subs encntr', 'Tak');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (60, 'Kids Crest', 'Varicose veins of left lower extremity with ulcer of calf', 'Tha Mai');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (61, 'Levothyroxine Sodium', 'Crushing injury of left thigh, initial encounter', 'Zaječí');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (62, 'Oxygen', 'Motorcycle passenger injured in collision w unsp mv in traf', 'Cipari');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (63, 'Allergies Southern US', 'Laceration of peroneal artery, right leg', 'Jiasi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (64, 'TC Instant Hand Sanitizer', 'Oth rheumatoid arthritis w rheumatoid factor of r shoulder', 'Chagoda');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (65, 'Allscale', 'Unsp injury of blood vessel of unspecified finger, sequela', 'Saint Helier');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (66, 'ELF Mineral Concealers SPF 15', 'Toxic effect of other pesticides, undetermined', 'Mogapi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (67, 'CLE DE PEAU BEAUTE SILKY FOUNDATION I', 'Other chronic osteomyelitis, right shoulder', 'Vaughan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (68, 'Technetium Tc99m Generator', 'Ped w convey injured in clsn w rail trn/veh in traf, sequela', 'Lajedo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (69, 'Pure Transformation Sheer Light', 'Flexion deformity, left ankle and toes', 'Bagulin');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (70, 'Metoprolol Tartrate', 'Dislocation and sprain of joints and ligaments at neck level', 'Sidomukti');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (71, 'Apis Bryonia Special Order', 'Mantle cell lymphoma, lymph nodes of axilla and upper limb', 'Jingpeng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (72, 'AMOREPACIFIC', 'Poisoning by expectorants, intentional self-harm, sequela', 'Independence');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (73, 'Kadian', 'Unsp fracture of unsp metacarpal bone, init for clos fx', 'Duyên Hải');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (74, 'BullFrog Super Block', 'Laceration with foreign body of right shoulder, init encntr', 'Balgatay');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (75, 'Ionite APF', 'Encounter for fit/adjst of unsp external prosthetic device', 'Tha Uthen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (76, 'Germicida', 'Traumatic amputation of other parts of head, sequela', 'Hanfeng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (77, 'Tretinoin', 'Laceration w/o fb of unsp toe w/o damage to nail, sequela', 'Nīkêh');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (78, 'NARS', 'Toxic eff of fluorine gas and hydrogen fluoride, acc, subs', 'Bulumulyo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (79, 'ELYMUS REPENS POLLEN', 'LeFort I fracture, initial encounter for closed fracture', 'Kraljevo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (80, 'Cefazolin', 'Nondisp longitud fx r patella, subs for clos fx w routn heal', 'Cerro Blanco');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (81, 'Hand Wash', 'Breakdown (mechanical) of urinary devices and implants, init', '''Ali Sabieh');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (82, 'Niravam', 'Person outsd bus inj in clsn w rail trn/veh nontraf, sequela', 'Xiaogang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (83, 'ATORVASTATIN CALCIUM', 'Nondisp fx of r tibial spine, subs for clos fx w routn heal', 'Labinot-Mal');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (84, 'Equaline Childrens Pain and Fever', 'Oth physeal fx lower end of r fibula, subs for fx w nonunion', 'Novais');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (85, 'Metoclopramide', 'Medial disloc of proximal end of tibia, right knee, init', 'Kochani');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (86, 'Pramipexole Dihydrochloride', 'Anterior cord syndrome at T11-T12, subs', 'Cengang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (87, 'Mucor/Aspergillus', 'Other superficial bite of breast, left breast, subs encntr', 'Yangfeng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (88, 'Amoxicillin', 'Sprain of calcaneofibular ligament of left ankle', 'Jezzîne');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (89, 'Midazolam HCl', 'Inflammatory polyps of colon', 'Barreiras');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (90, 'benzonatate', 'Adhes due to fb acc left in body fol unsp procedure, init', 'Betulia');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (91, 'Captopril', 'Unspecified subluxation and dislocation of toe', 'San Antonio de Los Altos');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (92, 'Rocephin', 'Nondisp fx of greater trochanter of l femr, 7thE', 'Pluak Daeng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (93, 'Losartan Potassium', 'Unspecified sprain of left index finger', 'Vinsady');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (94, 'English Walnut', 'Disp fx of navicular of right foot, subs for fx w routn heal', 'Fenshui');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (95, 'Ferrum sidereum 6', 'Toxic effect of venom of brown recluse spider, acc, sequela', 'Ayrihuanca');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (96, 'Morphine Sulfate', 'Bent bone of r rad, subs for opn fx type 3A/B/C w nonunion', 'Bandar-e Torkaman');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (97, 'Piperacillin and Tazobactam', 'Nondisp oblique fx shaft of unsp femr, 7thN', 'Kembang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (98, 'Apis Mell.', 'Nondisp oblique fx shaft of r tibia, 7thC', 'Xunqiao');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (99, 'Sterile Water', 'Obst due to fb acc left in body fol remov cath/pack, subs', 'Sarnów');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (100, 'Treatment Set TS351129', 'Other functional intestinal disorders', 'Aranas Sur');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (101, 'Aleve', 'Disp fx of med condyle of l tibia, 7thR', 'Jelisavac');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (102, 'childrens pain and fever', 'Abrasion of scrotum and testes', 'Újezd');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (103, 'equate nitetime severe', 'Abrasion of left little finger, initial encounter', 'Durham');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (104, 'Citalopram Hydrobromide', 'War op w unsp fire/conflagr/hot subst, civilian, subs', 'Shushi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (105, 'Verapamil Hydrochloride', 'Unsp fx shaft of right tibia, init for opn fx type 3A/B/C', 'Gustavia');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (106, 'Risperidone', 'Nondisp unsp condyle fx low end unsp femr, 7thF', 'Gumdag');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (107, 'Care One Original SPF 4 Lip Balm', 'Oth fracture of left lower leg, init for opn fx type I/2', 'Karangmelok');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (108, 'Argentum Quartz', 'Displ artic fx head of r femr, 7thH', 'Al ‘Āqir');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (109, 'DELFLEX', 'Atrioventricular block, complete', 'Balitai');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (110, 'Antibacterial Foaming Hand Sanitizer', 'Oth disorders of breast assoc w pregnancy and the puerperium', 'Olleros');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (111, 'Methscopolamine Bromide', 'Other specified effects of reduced temperature', 'Kamyshevka Vtoraya');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (112, 'Caldolor', 'Burn of first degree of left thumb (nail), initial encounter', 'Goodlands');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (113, 'COREG', 'Toxic effect of unsp alcohol, accidental, sequela', 'Chiryū');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (114, 'Edarbyclor', 'Oth disorders of bone development and growth, left ank/ft', 'Danzao');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (115, 'Lucky Instant Hand Sanitizer with Aloe Vera', 'Stress fracture, left tibia, subs for fx w delay heal', 'Mangochi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (116, 'Ambi Even and Clear Daily Moisturizer', 'Pnctr of abd wall w/o fb, unsp quadrant w/o penet perit cav', 'Gerakaroú');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (117, 'Treatment Set TS332256', 'Maxillary hyperplasia', 'Dijon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (118, 'Levofloxacin', 'Oth comp specific to multiple gest, first trimester, unsp', 'Dashtavan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (119, 'Moisuture Replenishing Broad Spectrum SPf 15', 'Driver of pk-up/van inj in clsn w oth mv nontraf, sequela', 'Victoria');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (120, 'Cat Pelt, Standardized', 'Abscess of tendon sheath, right lower leg', 'Leśnica');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (121, 'ShopRite Ni Calm', 'Aneurysmal bone cyst, right forearm', 'Nanortalik');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (122, 'Crayola Wild Blue Yonder Roll On Hand Sanitizer', 'Alcohol related disorders', 'Conceição do Coité');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (123, 'Sheep Sorrel', 'Fall into oth water striking wall causing oth injury, init', 'Vale de Touros');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (124, 'Omeprazole', 'Oth psychoactive substance use, unsp w sleep disorder', 'Mengxi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (125, 'Antina 40 (Number 48)', 'Other edema specific to newborn', 'Alzamay');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (126, 'Pramipexole Dihydrochloride', 'Fibrous dysplasia (monostotic), thigh', 'Igarapé Açu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (127, 'Quality Choice Chewable Antacid', 'Disp fx of med condyle of r femr, 7thJ', 'Ḩalāwah');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (128, 'Valacyclovir Hydrochloride', 'Open wound of right buttock', 'Santa María de Caparo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (129, 'Arnicare Value Pack', 'Eclampsia', 'Mosar');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (130, 'LBEL Couleur luxe rouge irresistible maximum hydration SPF 17', 'Contusion of anus', 'Andamui');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (131, 'METHIMAZOLE', 'Disp fx of lateral condyle of r femr, 7thE', 'Eiguliai');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (132, 'Zeel', 'Cocaine use, unspecified with cocaine-induced sleep disorder', 'Celeirós');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (133, 'Medium Dark Foundation SPF 15', 'Maternal care for other known or suspected poor fetal growth', 'Chegang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (134, 'Neomycin and Polymyxin B Sulfates and Dexamethasone', 'Anterior dislocation of left sternoclavicular joint', 'Khlong Khuean');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (135, 'Buspirone Hydrochloride', 'Unsp car occ injured in clsn w nonmtr vehicle in traf, subs', 'Tempuran');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (136, 'Codeine sulfate', 'Displaced fracture of neck of left radius, sequela', 'Pasirtundun');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (137, 'amlodipine besylate', 'Toxic effect of unsp seafood, intentional self-harm, subs', 'Antimácheia');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (138, 'pravastatin sodium', 'Paratyphoid fever C', 'Prosvet');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (139, 'Me-PB-Hyos', 'Unspecified entropion of left lower eyelid', 'Gaoliang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (140, 'Hydralazine Hydrochloride', 'Trichiasis without entropian right eye, unspecified eyelid', 'Letuyi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (141, 'NARS FOUNDATION', 'Contusion of left great toe with damage to nail, init encntr', 'Prosperidad');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (142, 'Viscumforce', 'Other specified injuries of unspecified foot, subs encntr', 'Pereira');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (143, 'CHAPSTICK LIPSHIELD 365', 'Opioid use, unsp w opioid-induc psych disorder w hallucin', 'Shangyang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (144, 'Omeprazole', 'Strain flxr musc/fasc/tend l little fngr at wrs/hnd lv, sqla', 'Delanggu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (145, 'Maximum Strength PMS Formula', 'Walked into wall', 'Kitcharao');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (146, 'Cetirizine Hydrochloride', 'Corrosion of third degree of left ankle', 'Beiyang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (147, 'Claforan', 'Inj unsp musc/fasc/tend at shldr/up arm, left arm, init', 'Kindersley');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (148, 'Climara', 'Pathological fracture in other disease, unspecified shoulder', 'San Marcos');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (149, 'Headache', 'Pnctr w foreign body of finger w/o damage to nail, subs', 'Beringin');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (150, 'Neutrogena Naturals Acne Foaming Scrub', 'Other hypertrophic osteoarthropathy, lower leg', 'Lajarik');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (151, 'Alcoholism', 'Disp fx of proximal phalanx of l thm, subs for fx w nonunion', 'Sumisip');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (152, 'Fluoxetine', 'Familial chondrocalcinosis, unspecified wrist', 'Jiangbu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (153, 'Amlodipine Besylate', 'Displaced dome fx unsp talus, subs for fx w delay heal', 'Wuyun');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (154, 'Be gone Insomnia', 'Passenger in hv veh injured in clsn w pedl cyc nontraf, subs', 'Blagoevgrad');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (155, 'Amlodipine Besylate', 'Adverse effect of other antipsychotics and neuroleptics', 'Khāngāh Dogrān');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (156, 'Ear Care', 'Inj extn musc/fasc/tend at forearm level, right arm, sequela', 'Riangderi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (157, 'AmerFresh', 'Family hx of malig neoplm of resp and intrathorac organs', 'Kiambu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (158, 'Banana Boat Ultra Defense Sheer Protect SPF 50', 'Ulcerative (chronic) pancolitis with abscess', 'Beizhang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (159, 'ziprasidone hydrochloride', 'Blister (nonthermal) of nose, sequela', 'Haicheng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (160, 'Neova', 'Underdosing of antipruritics, subsequent encounter', 'Kadipaten');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (161, 'Gas Relief', 'Displaced fracture of lateral condyle of unspecified tibia', 'Lapaz');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (162, 'CELL BOOSTING BB', 'Other specified injuries of unspecified ankle', 'Kinéta');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (163, 'Nu Skin Nu Colour', 'Disp fx of triquetrum bone, right wrist, init for clos fx', 'Mojosari');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (164, 'Neosporin Plus Pain Relief', 'Complete lesion at unsp level of cervical spinal cord, init', 'Darfield');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (165, 'Glyburide', 'Ocular lac/rupt w prolaps/loss of intraoc tissue, right eye', 'Guiuan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (166, 'Adderall', 'Pathological fracture in other disease, other site, sequela', 'Alfeizerão');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (167, 'TRICLOTREX-B', 'Other osteomyelitis, ankle and foot', 'Dongfeng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (168, 'FRAXINUS VELUTINA POLLEN', 'Placentitis, third trimester', 'Helixi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (169, 'Aloemint Skin Aid', 'War operations involving explosion of marine weapons', 'Chengbei');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (170, 'White Hickory', 'Other nondisplaced fracture of seventh cervical vertebra', 'Maceió');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (171, 'PROMACTA', 'Disorder of adrenal gland, unspecified', 'Landskrona');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (172, 'Tizanidine', 'Crohn''s disease, unspecified, with unspecified complications', 'Degerfors');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (173, 'Bethanechol Chloride', 'Torus fracture of lower end of left fibula', 'Rouen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (174, 'Childrens Allergy', 'Displacement of artificial heart, initial encounter', 'Simao');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (175, 'Degree', 'Other specified injuries of left ankle', 'Tangdukou');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (176, 'Peri-Colace', 'Unspecified sprain of thumb', 'Chalandrítsa');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (177, 'Cold Remedy', 'Puncture wound without foreign body of unsp elbow, sequela', 'Conceição da Barra');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (178, 'Blueberry Antibacterial Hand Wash', 'Pre-existing type 2 diabetes mellitus, in pregnancy', 'Montreuil');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (179, 'Ultra Nutrition Night', 'Oth fx low end r ulna, 7thN', 'Apucarana');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (180, 'Little Remedies Little Colds Mucus Relief Expectorant Melt Aways', 'Oth osteopor w crnt path fx, unsp site, 7thD', 'Skalbmierz');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (181, 'Zippity Doos', 'Oth prob rel to prim support group, inc family circumstances', 'Ciburial');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (182, 'healthy accents ibuprofen pm', 'Disp fx of greater trochanter of unsp femr, 7thP', 'Baryshevo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (183, 'Calcium Acetate', 'Poisoning by methylphenidate, assault, sequela', 'Legen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (184, 'Belucie Luxury Timeless Golden Age Night', 'Puncture wound w foreign body of thmb w damage to nail, subs', 'Dobrzyca');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (185, 'EXCEDRIN', 'Poisoning by unspecified systemic antibiotic, undetermined', 'General La Madrid');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (186, 'Potassium Chloride', 'Nondisp seg fx shaft of rad, unsp arm, 7thF', 'Anuling');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (187, 'Good Sense itchy eye', 'External constriction of unspecified forearm, sequela', 'Zharkent');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (188, 'FeverALL Children', 'Disp fx of anterior wall of left acetabulum, sequela', 'Bang Kaeo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (189, 'POPULUS DELTOIDES POLLEN', 'Nondisplaced intertroch fracture of right femur, sequela', 'Yongfeng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (190, 'Dicloxacillin Sodium', 'Poisoning by methadone, intentional self-harm', 'Uspenskoye');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (191, 'ALTHEUS', 'Crushing injury of face, subsequent encounter', 'Pyshchug');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (192, 'Carvedilol', 'Displ osteochon fx r patella, subs for clos fx w nonunion', 'Sapiranga');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (193, 'Haloperidol', 'Varicella pneumonia', 'Qinling Jieban');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (194, 'LEVITRA', 'Other infective (teno)synovitis, other site', 'Krasnyy Luch');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (195, 'Montelukast Sodium', 'Unspecified sprain of unspecified foot, initial encounter', 'Dayapan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (196, 'OBAGI C RX SYSTEM C CLARIFYING SERUM', 'Monoplg upr lmb fol unsp cerebvasc dis aff left nondom side', 'Banjar Asahduren');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (197, 'Pear Barlet Antibacterial Hand', 'Unsp trochan fx r femur, subs for opn fx type I/2 w malunion', 'Siikainen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (198, 'SULAR', 'Oth osteopor w crnt path fx, l ank/ft, 7thP', 'Obudovac');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (199, 'smart sense nicotine polacrilex', 'Local-rel idio epi w seiz of loc onset, ntrct, w stat epi', 'Verkhniy Mamon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (200, 'Zolpidem Tartrate', 'Dvtrcli of both small and lg int w/o perf or abscess w bleed', 'Gómez');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (201, 'Orphenadrine Citrate', 'Cont preg aft spon abort of one fts or more, first tri, fts3', 'Trà Ôn');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (202, 'Tranylcypromine Sulfate', 'Acute bronchiolitis', 'Jablah');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (203, 'NuGLOW', 'Displ intertroch fx l femr, 7thH', 'Hallsberg');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (204, 'Cargo Tinted Moisturizer SPF 20', 'Hypertension secondary to endocrine disorders', 'Tanahmerah');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (205, 'losartan potassium', 'Sltr-haris Type III physl fx lower end rad, unsp arm, sqla', 'Xingfu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (206, 'Systane', 'String or thread causing external constriction, sequela', 'Xishui');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (207, 'FRAXINUS AMERICANA POLLEN', 'Injury of greater saphenous vein at lower leg level', 'Wuku');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (208, 'Oxygen', 'Contusion of right shoulder', 'Ferreira do Alentejo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (209, 'Mometasone Furoate', 'Intcran inj w LOC >24 hr w/o ret consc w surv, subs', 'Muaralabuh');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (210, 'Hygienic Cleansing Pads', 'Nondisp spiral fx shaft of ulna, r arm, 7thH', 'San Enrique');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (211, 'Modafinil', 'Dislocation of unsp parts of left shoulder girdle, init', 'Kwikila');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (212, 'Gatifloxacin', 'Displ unsp condyle fx low end l femr, 7thQ', 'Mexico');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (213, 'Rivastigmine Tartrate', 'Unsp injury of flexor musc/fasc/tend thmb at forearm level', 'Yanghong');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (214, 'Gabapentin', 'Microcystoid degeneration of retina', 'Goiatuba');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (215, 'Childrens Mucinex', 'Unsp tear of unsp meniscus, current injury, unsp knee, init', 'Wolonio');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (216, 'Softlips Coconut', 'Displaced fracture of cuboid bone of left foot', 'Melekyne');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (217, 'Salicylic Acid', 'Unspecified superficial injury of left wrist, sequela', 'Inglewood');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (218, 'Thiothixene', 'War op involving dest arcrft due to onboard fire, milt, init', 'Yunxi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (219, 'Methocarbamol', 'Stimulant laxatives', 'Besançon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (220, 'good sense ibuprofen', 'Unsp traumatic displ spondylolysis of fifth cervcal vertebra', 'Gayam');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (221, 'health mart aspirin', 'Primary open-angle glaucoma, right eye, stage unspecified', 'Charras');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (222, 'CD DiorSkin Forever Compact Flawless Perfection Fusion Wear Makeup SPF 25 - 023', 'Coma scale, best motor response, extension', 'Norcasia');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (223, 'Diltiazem Hydrochloride', 'Oth injury of vein at forearm level, unsp arm, sequela', 'Wufeng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (224, 'Famotidine', 'Nondisp midcervical fx r femur, init for opn fx type 3A/B/C', 'Zhaocun');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (225, 'Low-Ogestrel', 'Injury of lateral plantar nerve, unspecified leg, sequela', 'Naryn');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (226, 'Umcka Original ColdCare', 'Displ subtrochnt fx r femr, 7thE', 'Ḑubāh');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (227, 'Loratadine ODT', 'Oth traum nondisp spondylolysis of fourth cervcal vert, init', 'Youxi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (228, 'Asthma Rx', 'Displ Maisonneuve''s fx l leg, subs for clos fx w delay heal', 'Kardítsa');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (229, 'ESIKA HYDRACOLOR 2 IN 1 HIGHLY MOISTURIZING AND COLORING SPF 25', 'Superficial foreign body, left great toe, sequela', 'Śliwice');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (230, 'Cytra-K', 'Nondisp seg fx shaft of rad, r arm, 7thE', 'Acton Vale');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (231, 'Zosyn', 'Nondisp fx of shaft of 4th MC bone, l hand, 7thG', 'Puncan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (232, 'AFRICA BIRD HOMME ALL IN ONE MOISTURIZER', 'Burn of third degree of right knee, sequela', 'Ladner');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (233, 'Menstrual Relief', 'Oth injury of other blood vessels at forearm level, left arm', 'Las Varas');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (234, 'Cardiac Support', 'Displacmnt of cardiac and vascular devices and implnt, subs', 'Pisarzowice');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (235, 'Moexipril Hydrochloride and Hydrochlorothiazide', 'Sltr-haris Type I physeal fx unspecified metatarsal, init', 'Liuche');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (236, 'Olive Pollen', 'Atrioventricular block, complete', 'Mengjia');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (237, 'Good Sense Antacid', 'Struck by horse, sequela', 'Asadābād');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (238, 'Levothyroxine Sodium', 'Unspecified disorder of circulatory system', 'Na Klang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (239, 'DERMAGUNGAL', 'Subluxation of unsp interphaln joint of left thumb, subs', 'Neiva');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (240, 'ACT Anticavity Fluoride Cinnamon', 'Oth stimulant use, unsp w stim-induce sexual dysfunction', 'Kamakura');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (241, 'Mycratine', 'Poisoning by other psychodysleptics, undetermined, sequela', 'Pakemitan Dua');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (242, 'Ultra Seal Bacitracin', 'Noninflammatory disorder of uterus, unspecified', 'Gareba');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (243, 'NICE', 'Exposure to sofa fire', 'Lyon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (244, 'Tragacanth Gum', 'Perianal venous thrombosis', 'Atlanta');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (245, 'Lyrica', 'Sequelae of genitourinary tuberculosis', 'Imider');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (246, 'ATACAND', 'Intermittent monocular esotropia, left eye', 'Al Karmil');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (247, 'Ropinirole Hydrochloride', 'Acute bronchiolitis, unspecified', 'Leribe');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (248, 'Glyburide and Metformin Hydrochloride', 'Poisoning by pyrazolone derivatives, self-harm, subs', 'Gorobinci');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (249, 'Lansoprazole', 'Unspecified disorder of lens', 'Edineţ');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (250, 'Flawless Finish Dual Perfection Makeup SPF 8 Ivory', 'Adult psychological abuse, suspected, subsequent encounter', 'Tangjia');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (251, 'COTTONTAILS', 'Pnctr w/o fb of l little finger w damage to nail, init', 'Hayama');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (252, 'Pecan Nut', 'Occ of rail trn/veh inj by fall from rail trn/veh, sequela', 'Otan Aiyegbaju');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (253, 'CANIS LUPUS FAMILIARIS SKIN', 'Intraop hemor/hemtom of a ms structure comp a procedure', 'Paghmān');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (254, 'good sense cold', 'Driver of hv veh injured in clsn w pedl cyc nontraf, init', 'Outeirô');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (255, 'Acne/Pimple Control', 'Spastic ectropion of left eye, unspecified eyelid', 'Mikhnëvo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (256, 'Aspergillus repens', 'Pedestrian on foot injured in collision w skateboarder, subs', 'Koslan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (257, 'Hydrochlorothiazide', 'Monocular esotropia with other noncomitancies, right eye', 'Kivijärvi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (258, 'Milrinone Lactate', 'Other injury of celiac artery, subsequent encounter', 'Dobrich');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (259, 'Mesalamine', 'Calcific tendinitis, hand', 'Ciodeng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (260, 'Iodine Plus Capsule', 'Other subjective visual disturbances', 'Kovdor');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (261, 'Dilaudid', 'Folds and rupture in Bowman''s membrane, bilateral', 'Petrozavodsk');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (262, 'Nabumetone', 'Underdosing of histamine H2-receptor blockers', 'Gorskaya');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (263, 'cold relief', 'Tox eff of nitro & oth nitric acids and esters, undet, subs', 'Yolöten');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (264, 'Paroxetine', 'Displ apophyseal fx unsp femr, 7thJ', 'Stepnogorsk');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (265, 'Pain Relief', 'Partial retinal artery occlusion, left eye', 'Suozhen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (266, 'L Dopa', 'Contusion of right breast, sequela', 'Brdów');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (267, 'Pure Gel', 'Skeletal fluorosis, forearm', 'Juxing');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (268, 'Ketoconazole', 'Upper abdominal pain, unspecified', 'Estrela');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (269, 'Healthy Accents Mucus Relief', 'Placentitis, unspecified trimester, other fetus', 'Wenfeng Zhen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (270, 'THE TREATMENT POWDER FOUNDATION', 'Military operations involving fragments from weapons', 'Jeonju');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (271, 'LenzaPatch', 'War operations involving gasoline bomb, milt, init', 'Baie-D''Urfé');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (272, 'Flu Relief Therapy Night Time', 'Lacerat abd wall w fb, right low q w/o penet perit cav, init', 'Blučina');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (273, 'Exjade', 'Oth fracture of first lumbar vertebra, init for clos fx', 'South Bend');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (274, 'KETOROLAC TROMETHAMINE', 'Incarcerated fx of med epicondyl of r humer, 7thG', 'Nyuksenitsa');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (275, 'OHUI Sun Science intensive sunblock cake EX', 'Sprain of interphalangeal joint of left little finger, subs', 'Llusco');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (276, 'Procardia', 'Type 2 diabetes mellitus with other skin complications', 'Baisha');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (277, 'Ipratropium Bromide', 'Brown-Sequard syndrome at C4, sequela', 'Santo Antônio de Posse');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (278, 'Cholestyramine', 'External constriction, left lesser toe(s), subs encntr', 'Shentong');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (279, 'Z-COF', 'Complete traumatic amputation of unsp foot, level unsp, init', 'Pereiro');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (280, 'TENEX', 'Pedestrian injured in collision w 2/3-whl mv nontraf', 'Mababanaba');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (281, 'equaline', 'Burn of 3rd deg mu sites of unsp wrist and hand, subs', 'Racławice');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (282, 'Frankincense and Myrrh Sciatica', 'Matern care for oth or susp poor fetl grth, 2nd tri, fts5', 'Cliza');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (283, 'SELEGILINE HYDROCHLORIDE', 'Disp fx of shaft of unsp MC bone, subs for fx w routn heal', 'la Massana');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (284, 'Furosemide', 'Path fx in oth dis, unsp tibia & fibula, 7thG', 'Mae Chan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (285, 'Stavudine', 'Other superficial injuries of ankle', 'Pangian');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (286, 'LOreal Professionnel Paris', 'Explosion of bicycle tire', 'Dassa-Zoumé');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (287, 'Ala-Septic', 'Legal intervention involving baton, suspect injured, init', 'Mojogajeh');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (288, 'Robaxin', 'Barton''s fracture of unspecified radius', 'Naxos');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (289, 'Lovastatin', 'Patellar tendinitis, left knee', 'Kozlovice');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (290, 'Carbamazepine', 'Occ of rail trn/veh inj in collisn/hit by roll stok, init', 'Stockholm');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (291, 'Lyrica', 'Nondisp oblique fx shaft of l ulna, 7thD', 'Krajan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (292, 'Ready Foundation', 'Malignant neoplasm of conn and soft tissue of trunk, unsp', 'Xinhua');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (293, 'Chestnut Oak', 'Nondisp fx of greater trochanter of l femr, 7thR', 'Buenavista');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (294, 'Butalbital, aspirin, and caffeine', 'Portal vein-hepatic artery fistula', 'Krajan Sumurtawang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (295, 'ANTIBACTERIAL FOAMING', 'Maternal hypotension syndrome, third trimester', 'Paris 13');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (296, 'VENLAFAXINE', 'Toxic effect of homologues of benzene, accidental, sequela', 'Houmen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (297, 'Chorionic Gonadotropin', 'Ped on sktbrd inj pick-up truck, pk-up/van, unsp, sequela', 'Kushnarënkovo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (298, 'Gabapentin', 'Intraop hemor/hemtom of eye and adnexa comp an opth proc', 'Tunggulsari');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (299, 'OXYMETAZOLINE HYDROCHLORIDE', 'Occupant of powered streetcar injured in transport accident', 'Talacogon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (300, 'Hydrogen Peroxide', 'Dislocation of unspecified internal joint prosthesis', 'Saint-Félicien');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (301, 'infants anti gas', 'Unspecified injury of dorsal vein of left foot, subs encntr', 'Phoenix');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (302, 'Dermarest', 'Unsp inj musc/tend post grp at low leg level, left leg, sqla', 'Kiukainen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (303, 'Varicose Veins', 'Open bite, left foot, sequela', 'Wu’an');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (304, 'Sucralfate', 'Occup of pk-up/van inj in clsn w nonmtr veh in traf, sqla', 'Tokonou');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (305, 'No7 Protect and Perfect Day Cream SPF 15', 'Fracture of unspecified phalanx of left little finger', 'Tarqūmyā');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (306, 'Naproxen', 'Lacerat unsp blood vessel at lower leg level, right leg', 'Cedar Rapids');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (307, 'DIAMITE', 'Corrosion of third degree of left thumb (nail), subs encntr', 'Norton');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (308, 'good neighbor pharmacy cold', 'Open bite of right great toe w/o damage to nail, subs encntr', 'Xiangyang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (309, 'Miracle Plus Anti-Fungal', 'Poisoning by thyroid hormones and sub, undet, sequela', 'Washington');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (310, 'Molds, Rusts and Smuts, Rhizopus nigricans', 'Toxic effect of tobacco cigarettes, self-harm, init', 'Castanheira');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (311, 'KINESYS', 'Passenger in hv veh injured in clsn w ped/anml nontraf, subs', 'Dong’ao');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (312, 'Naturasil Gout', 'Family history of blindness and visual loss', 'Santa Luċija');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (313, 'Isopropyl Alcohol', 'Other physeal fracture of unspecified metatarsal, sequela', 'Sendang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (314, 'Sun Shades Lip Balm', 'Other cytomegaloviral diseases', 'Yevlakh');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (315, 'Hyoscyamine Sulfate', 'Occupant (driver) of 3-whl mv injured in unsp nontraf, subs', 'Shawan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (316, 'NICOTINE', 'Disp fx of less trochanter of unsp femr, 7thP', 'Horvati');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (317, 'Head and Shoulders', 'Oth injury due to oth accident on board canoe or kayak, init', 'Tianhu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (318, 'Pleo Pin', 'Complete physeal arrest, right distal femur', 'Leżajsk');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (319, 'Meclizine Hydrochloride', 'Mechanical ectropion of right upper eyelid', 'Drachten');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (320, 'Symphytum Stannum', 'Unspecified pre-eclampsia, complicating childbirth', 'Kakanj');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (321, 'Health Smart Blue Ice Topical Analgesic', 'Systemic antibiotics', 'Kvasice');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (322, 'VALTREX', 'Wedge comprsn fx unsp thor vert, subs for fx w routn heal', 'Palompon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (323, 'Nexavar', 'Driver of 3-whl mv injured in nonclsn trnsp accident nontraf', 'Yuezhao');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (324, 'ACONITUM LYCOCTONUM', 'Driver of 3-whl mv inj pk-up truck, pk-up/van in traf, sqla', 'Vysoké nad Jizerou');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (325, 'Bumetanide', 'Tinnitus, bilateral', 'Stegna');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (326, 'telmisartan and hydrochlorothiazide', 'Underdosing of alpha-adrenoreceptor antagonists, init encntr', 'Jam');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (327, 'SIMVASTATIN', 'War op w explosn due to acc disch of own munit, milt, subs', 'Крушево');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (328, 'buprenorphine hydrochloride and naloxone hydrochloride dihydrate', 'Inj unsp blood vessel at forearm level, unsp arm, sequela', 'Sopo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (329, 'Ammonium Lactate', 'Poisn by analeptics and opioid receptor antag, slf-hrm, sqla', 'Ekibastuz');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (330, 'LANOXIN', 'Pressure ulcer of other site, stage 2', 'Bitola');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (331, 'sunmark ibuprofen', 'Fall into oth water striking bottom causing drown', 'Preobrazhenka');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (332, 'Degree', 'Contact with liquid air', 'Morales');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (333, 'Neutrogena Nourishing Eye Quad', 'Fall from other pedestrian conveyance, initial encounter', 'Balabag');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (334, 'PHENADOZ', 'Displaced segmental fracture of shaft of right tibia, init', 'Funtua');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (335, 'ACACIA', 'Laceration w fb of r rng fngr w/o damage to nail, subs', 'Bielsk Podlaski');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (336, 'Chlorpromazine Hydrochloride', 'Disp fx of nk of r rad, subs for opn fx type I/2 w nonunion', 'Kalmar');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (337, 'Clorox CareConcepts Bed Bath and Hygiene', 'Hypertrophy of uterus', 'Qijiaxi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (338, 'Benzonatate', 'Traum hemor right cerebrum w LOC of 30 minutes or less', 'Yingzhou');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (339, 'Smarth', 'Type 1 diab w prolif diab rtnop w trctn dtch macula, r eye', 'Bekondo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (340, 'RANITIDINE', 'Nondisp seg fx shaft of unsp tibia, 7thD', 'São Raimundo Nonato');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (341, 'Ondansetron', 'Felty''s syndrome, knee', 'Pidhaytsi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (342, 'REVITALIZING C I2PL STEMCELL BB', 'Chronic frontal sinusitis', 'Amuru');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (343, 'cilostazol', 'Insect bite (nonvenomous) of anus', 'San Pedro');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (344, 'LEADER NICOTINE TRANSDERMAL SYSTEM', 'Bone donor', 'Sambungjaya');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (345, 'COPAXONE', 'Stiffness of right shoulder, not elsewhere classified', 'Frei');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (346, 'Tegretol', 'Poisoning by appetite depressants, accidental, init', 'Geghanist');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (347, 'Keppra', 'Laceration of lung, unspecified, initial encounter', 'Binawara');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (348, 'Adinos 40 (Number 125)', 'Unsp fracture of unsp ilium, init encntr for closed fracture', 'Gandu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (349, 'SIMVASTATIN', 'Complete traumatic amp of r forearm, level unsp, sequela', 'Krahës');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (350, 'Valsartan and hydrochlorothiazide', 'Separation anxiety disorder of childhood', 'Byala');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (351, 'Nicotine', 'Coma scale, eyes open, spontaneous', 'Boleszkowice');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (352, 'Amoxicillin', 'Lacerat flexor musc/fasc/tend l thm at forarm lv, sequela', 'Djounie');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (353, 'Methylergonovine Maleate', 'External constriction of right front wall of thorax', 'Sopron');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (354, 'Promethazine Hydrochloride', 'Adverse effect of antipruritics, initial encounter', 'Trelleborg');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (355, 'FUSARIUM OXYSPORUM VASINFECTUM', 'Pathological fracture, unsp site, init encntr for fracture', 'Las Americas');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (356, 'Hydralazine Hydrochloride', 'Prsn brd/alit a car injured in collision w van, sequela', 'Junxi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (357, 'Red Oak', 'Underdosing of anticoagulants, initial encounter', 'Bohicon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (358, 'leader nite time', 'Congenital malform of gallbladder, bile ducts and liver', 'Viamão');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (359, 'Cyclopentolate Hydrochloride', 'Nondisp trimalleol fx l low leg, 7thE', 'Maracaibo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (360, 'Metoprolol Tartrate', 'Other specified disorders of tendon, right hip', 'Pongkor');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (361, 'Medique Alcalak', 'Minor lacerat femor vein at hip and thi lev, unsp leg, init', 'Palermo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (362, 'BABOR HSR Lifting Eye Cream', 'Insect bite (nonvenomous) of lip', 'Suwaru');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (363, 'CareOne Pain Relief', 'Corrosion of third degree of right foot, sequela', 'Staryy Merchyk');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (364, 'Fluvoxamine Maleate', 'Lead-induced gout, multiple sites', 'Dodoma');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (365, 'Helium', 'Irritant contact dermatitis due to metals', 'Dedenëvo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (366, 'Folic Acid', 'Pasngr on bus inj in clsn w statnry object in traf, sequela', 'Sinjil');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (367, 'Cactus Crataegus', 'Subluxation of C7/T1 cervical vertebrae, subs encntr', 'Truskavets');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (368, 'Panama Jack', 'Milt op involving explosion of torpedo, military personnel', 'El Corozo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (369, 'DILAUDID', 'Laceration of musc/fasc/tend prt biceps, right arm, init', 'Novoul’yanovsk');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (370, 'Radiogardase', 'Crushing injury of unspecified elbow, sequela', 'Pont-à-Mousson');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (371, 'Quinapril Hydrochloride', 'Malignant neoplasm of aortic body and other paraganglia', 'Bremen');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (372, 'cold and flu relief', 'Laceration of other urinary and pelvic organ, init encntr', 'Yangshufang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (373, 'Valacyclovir Hydrochloride', 'Corrosion of third degree of left wrist, subs encntr', 'Kuzhu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (374, 'AcneFree Clear Skin Treatments', 'Personal history of malignant neoplasm of endocrine glands', 'Tulsa');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (375, 'Diltiazem Hydrochloride', 'Poisoning by antirheumatics, NEC, accidental, subs', 'Guri i Zi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (376, 'Ranitidine', 'Absence of family member due to military deployment', 'Łazy');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (377, 'Night Time Day Time', 'Displ oth fx tuberosity of l calcaneus, 7thP', 'Jinglou');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (378, 'FIBRICOR', 'Car driver injured in collision w 2/3-whl mv nontraf', 'Marcos Juárez');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (379, 'TONYMOLY KISS KISS LIP ESSENCE BALM', 'Late congenital syphilitic arthropathy', 'Wesoła');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (380, 'Promethazine Hydrochloride', 'Oth physeal fracture of upper end of right femur, init', 'Romblon');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (381, 'Ramipril', 'Torus fracture of upper end of left tibia', 'Karangmulyo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (382, 'Allopurinol', 'Inj unsp blood vess at hip and thi lev, left leg, sequela', 'Karara');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (383, 'SAFEWAY CARE', 'Struck by basketball, sequela', 'Zhongcun');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (384, 'Diltiazem Hydrochloride', 'Cochlear otosclerosis, left ear', 'Kol’chugino');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (385, 'Instant Hand Sanitizer - Original', 'Toxic effect of venom of other venomous lizard, assault', 'Cilebang Satu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (386, 'Sensipar', 'Tympanosclerosis, left ear', 'Viale');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (387, 'Quinidine Sulfate', 'Displ longitud fx right patella, subs for clos fx w malunion', 'Montenegro');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (388, 'Sodium Chloride for Irrigation', 'Displ oblique fx shaft of l femr, 7thM', 'Daytona Beach');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (389, 'good neighbor pharmacy Lice', 'Animal-rider injured in collision w ped/anml, sequela', 'Xialu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (390, 'Topex', 'Nondisp bicondylar fx l tibia, 7thM', 'San Marcos');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (391, 'Suave', 'Local infection due to central venous catheter, sequela', 'Kemisē');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (392, 'Methenamine Hippurate', 'Other rupture of muscle (nontraumatic)', 'Riachão das Neves');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (393, 'Health Mart Pharmacy Hydrocortisone', 'Inj musc/fasc/tend at wrs/hnd lv, unsp hand, sequela', 'Sainyabuli');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (394, 'Felodipine', 'Otitis media, unspecified', 'Jiagao');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (395, 'Xylocaine-MPF', 'Cocaine abuse with intoxication with delirium', 'Junxi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (396, 'Molds - Mold Mix 4', 'I/I react d/t other nrv sys device, implnt or graft, subs', 'As Suqaylibīyah');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (397, 'Mercurius auratus 15 Special Order', 'Milt op involving explosn of marine weapons, civilian, subs', 'Paagahan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (398, 'Rue21 Ocean Anti-Bacterial Hand Sanitizer', 'Fracture of sternal end of clavicle', 'Cherga');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (399, 'Pier 1 Imports Granny Smith Apple Anti-bacterial Hand Wash', 'Other specified diabetes mellitus without complications', 'Chicago');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (400, 'Argentum Malachite Athletes Foot Relief', 'Facial myokymia', 'Padangcermin');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (401, 'Fosinopril Sodium', 'External constriction of left upper arm, subs encntr', 'El Lolo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (402, 'triple antibiotic', 'Displ oblique fx shaft of unsp rad, 7thN', 'Rundeng');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (403, 'Black Oak', 'Other injury of right kidney, subsequent encounter', 'Bellavista');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (404, 'Tussi Pres', 'Maternal care for Anti-A sensitization, third trimester', 'Khotynets');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (405, 'MINERALIZE FOUNDATION', 'Acute megakaryoblastic leukemia', 'San Juan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (406, 'Phytolacca Kit Refill', 'Asphyxiation due to hanging, intentional self-harm, init', 'Sumbuya');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (407, 'Ibuprofen', 'Counseling for family member of alcoholic', 'Fovissste');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (408, 'PRENATAL PLUS', 'Other osteonecrosis, right humerus', 'Sykiés');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (409, 'CAPTOPRIL', 'Foreign body granuloma of the skin and subcutaneous tissue', 'Tuanjie');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (410, 'Latrix', 'Fall into swim pool strk surfc causing oth injury, sequela', 'Permas');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (411, 'Tramadol Hydrochloride', 'Other problems related to life management difficulty', 'Las Vegas');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (412, 'Russian Thistle', 'Oth fx of low end l rad, 7thH', 'Kosikha');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (413, 'Acetaminophen', 'Unsp malignant neoplasm skin/ unsp upper limb, inc shoulder', 'Newport News');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (414, 'Thyrostat', 'Paralytic calcifcn and ossification of muscle, right hand', 'Lexington');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (415, 'Hydralazine Hydrochloride', 'Segmental and somatic dysfunction of lumbar region', 'Karachi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (416, 'Colic Complex', 'Other ovarian cyst, unspecified side', 'Haz-Zebbug');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (417, 'Potassium Chloride', 'Foreign body in vulva and vagina, initial encounter', 'Nong Don');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (418, 'LOreal Paris Advanced Suncare Invisible Protect Dry 50 Plus Broad Spectrum SPF 50 Plus Sunscreen', 'Aftercare following explantation of shoulder jt prosthesis', 'Fengyuan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (419, 'Flomax', 'Oth parlyt synd fol oth cerebvasc dis aff right nondom side', 'Valašská Polanka');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (420, 'Aspirin', 'Disloc of interphaln joint of left lesser toe(s), sequela', 'Ebetsu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (421, 'Alcohol Prep Swab with Pain Relief', 'Pnctr w/o foreign body of left eyelid and periocular area', 'Căuşeni');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (422, 'Levetiracetam', 'Disp fx of lateral condyle of unsp tibia, 7thC', 'Temryuk');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (423, 'Western Water Hemp', 'Calcium deposit in bursa, right ankle and foot', 'Pangawaren');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (424, 'Warts - Moles - Skin Tags', 'Laceration of ulnar artery at wrs/hnd lv of left arm, subs', 'Lille');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (425, 'FLOVENT', 'Open bite of unspecified buttock, subsequent encounter', 'Janaka');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (426, 'Severe Cold and Flu', 'I/I react d/t nephrostomy catheter, subsequent encounter', 'Mountain View');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (427, 'Acetic Acid', 'Edema of bilateral orbit', 'Río Hondo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (428, 'Orajel for Cold Sores', 'Sltr-haris Type I physl fx low end humer, l arm, 7thK', 'Faqīrwāli');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (429, 'Trimethoprim', 'Nondisp fx of head of unsp rad, 7thR', 'Savran’');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (430, 'DG Health Cold Head Congestion', 'Early-onset cerebellar ataxia', 'Haarlem');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (431, 'Treatment Set TS332507', 'Laceration w fb of left thumb w/o damage to nail, sequela', 'Mysove');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (432, 'Quality Choice night time severe cold and cough', 'Kaschin-Beck disease, right shoulder', 'Pavlovskaya');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (433, 'Gengraf', 'Person injured in oth nonclsn trnsp acc w mtr veh, nontraf', 'Ko Samui');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (434, 'White Birch', 'Corrosion of second degree of left hand, unsp site, subs', 'Gontar');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (435, 'Dexamethasone', 'Unspecified injury of body of pancreas', 'Barroco');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (436, 'Head and Shoulders', 'Unsp injury of ulnar artery at forarm lv, unsp arm, sequela', 'Maoming');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (437, 'Aspir Low', 'Nondisp fx of intermed cuneiform of l ft, 7thP', 'Kut Chap');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (438, 'Atenolol', 'War op involving fragments from munitions, milt, init', 'Polanka Wielka');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (439, 'Haloperidol', 'Peripheral T-cell lymphoma, not classified, unspecified site', 'Nangaroro');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (440, 'Insects (whole body), Fire Ant Mix', 'Burn of esophagus, sequela', 'Nihaona');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (441, 'Talwin', 'Nondisp fx of med cuneiform of l ft, 7thG', 'Yëlkino');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (442, 'Moore Medical Cherry Cough Suppressant/Anesthetic Drops', 'Toxic effect of methanol, undetermined, sequela', 'Pamiątkowo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (443, 'Triamterene hydrochlorothiazide', 'Disp fx of olecran pro w/o intartic extn unsp ulna, 7thR', 'Nueva Esperanza');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (444, 'Spironolactone', 'Displ spiral fx shaft of humer, r arm, 7thP', 'Yafan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (445, 'Diaper Rash', 'Oth fracture of left great toe, subs for fx w delay heal', 'Rubizhne');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (446, 'Repaglinide', 'Laceration of muscle, fascia and tendon of left hip, subs', 'Yezhi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (447, 'Nystatin', 'Postproc seroma of unsp and adnexa following other procedure', 'Huangyang');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (448, 'Vichy Laboratoires', 'Partial traumatic amputation of left breast, sequela', 'El Aguilar');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (449, 'Oxytocin', 'Allergic contact dermatitis due to animal (cat) (dog) dander', 'Šenčur');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (450, 'NO-AD SPF45 Continuous Mist Sunscreen', 'Unsp tear of unsp meniscus, current injury, unsp knee, init', 'Vårby');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (451, 'Ranitidine', 'Pedl cyc passenger injured in clsn w unsp mv nontraf, subs', 'La Sebala du Mornag');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (452, 'flormar REBORN FOUNDATION SUNSCREEN BROAD SPECTRUM SPF 20 SF13 Nude Ivory', 'Asphyxiation due to being trapped in a car trunk, assault', 'Camatagua');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (453, 'Surgicide', 'Psoriatic juvenile arthropathy', 'Changping');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (454, 'Moisture Renew', 'Nondisp suprcndl fx w/o intrcndl extn low end r femr, 7thN', 'Tumba');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (455, 'Nortriptyline Hydrochloride', 'Burn due to localized fire on board other powered watercraft', 'Sikur');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (456, 'Amlodipine Besylate', 'Healthcare provider, perpetrator of maltreatment and neglect', 'Vidyayevo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (457, 'Oxybutynin Chloride', 'Nondisp fx of proximal phalanx of right lesser toe(s), init', 'Bama');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (458, 'Topiramate', 'Lymphangioleiomyomatosis', 'Svobody');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (459, 'Anti-Bacterial Hand', 'Infective myositis, right ankle', 'Kallíthiron');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (460, 'Flu Relief Therapy Day Time', 'Sprain of radiocarpal joint of unsp wrist, subs encntr', 'Södertälje');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (461, 'Methocarbamol', 'Other specified rheumatoid arthritis, right hip', 'Gongpo');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (462, 'Chlorhexidine Gluconate', 'Oth physl fx low end rad, left arm, subs for fx w routn heal', 'Tipaz');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (463, 'Treatment Set TS330316', 'Abrasion of oral cavity, subsequent encounter', 'Bela Vista');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (464, 'Dipyridamole', 'Sprain of interphalangeal joint of toe', 'Ágios Matthaíos');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (465, 'CLARINS Extra-Comfort Broad Spectrum SPF 15 Sunscreen Tint 112', 'Poisn by unsp primarily systemic and hematolog agent, acc', 'Saint Helier');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (466, 'Losartan Potassium', 'Lac w/o fb of abd wl, periumb rgn w/o penet perit cav, sqla', 'Soriano');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (467, 'Doxorubicin Hydrochloride', 'Cutaneous nocardiosis', 'Trnovlje pri Celju');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (468, 'ATORVASTATIN CALCIUM', 'Inj conjunctiva and corneal abrasion w/o fb, unsp eye, subs', 'Franco da Rocha');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (469, 'Norethindrone', 'Nondisp fx of lateral epicondyl of unsp humer, 7thP', 'Manalu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (470, 'Pollens - Grasses, Corn, Cultivated Zea mays', 'Other chronic nonsuppurative otitis media, left ear', 'Santa Teresa');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (471, 'Losartan Potassium and Hydrochlorothiazide', 'Diffuse acute ischemia of intestine, part unspecified', 'Nova Kakhovka');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (472, 'Western Family', 'Mech compl of ventricular intracranial shunt, subs', 'Melfi');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (473, 'Galantamine', 'Transient synovitis', 'Nedryhayliv');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (474, 'NAPROXEN SODIUM', 'Blister (nonthermal), right lower leg', 'Nakambala');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (475, 'AC Out Spot stOp Serum', 'Contusion of lung, unilateral, initial encounter', 'Stanisław Górny');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (476, 'Allerpoll', 'Adverse effect of glucocort/synth analog, subs', 'Hisings Kärra');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (477, 'Tenzer', 'Struck by chicken', 'Ombarade');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (478, 'DEXTROAMPHETAMINE SULFATE', 'Sltr-haris Type I physl fx upr end r fibula, 7thD', 'Balboa');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (479, 'FormuCare Aspirin', 'Complete placenta previa with hemorrhage, unsp trimester', 'San Francisco');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (480, 'BabyGanics Alcohol Free Foaming Hand Sanitizer', 'Rheumatoid vasculitis w rheumatoid arthritis of right elbow', 'Tiebukenwusan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (481, 'Berkley and Jensen Nasal Decongestant PE', 'Nondisp commnt fx shaft of ulna, unsp arm, 7thB', 'Utrecht (stad)');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (482, 'Herbal UTAPLAS.TN', 'Tuberculosis of eye, unspecified', 'Varberg');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (483, 'Dawn Ultra Antibacterial Hand', 'Oth disrd of amniotic fluid and membrns, unsp tri, fetus 1', 'Frutillar');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (484, 'Carvedilol', 'Toxic effect of inorganic substances, intentional self-harm', 'Longhua');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (485, 'Allopurinol', 'Sexual abuse complicating pregnancy, unspecified trimester', 'Zhangdan');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (486, 'Chlordiazepoxide Hydrochloride', 'Pnctr w foreign body of l idx fngr w/o damage to nail, init', 'Amparafaravola');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (487, 'Academy Sports Outdoors SUNSCREEN CONTINUOUS SPORT BROAD SPECTRUM SPF 50 Water-Resistant', 'Toxic eff of nitrodrv/aminodrv of benzn/homolog, undet, subs', 'Tisul’');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (488, 'Phenytoin Sodium', 'Oth injury of dorsal vein of unspecified foot, init encntr', 'Ginebra');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (489, 'Sensorcaine', 'Oth fx right patella, subs for opn fx type I/2 w nonunion', 'Jaguaquara');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (490, 'ANTIBACTERIAL HAND SP WITH LIGHT MOISTURIZERS REFILL', 'Charcot''s joint, right shoulder', 'Karpacz');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (491, 'Atenolol', 'Leakage of heart valve prosthesis, sequela', 'Wangqu');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (492, 'MICONAZOLE', 'Toxic effect of beryllium and its compounds, assault, subs', 'Hirosaki');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (493, 'Ponderosa Pine', 'Nondisplaced avulsion fracture (chip fracture) of left talus', 'Lewopao');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (494, 'quetiapine fumarate', 'Toxic effect of herbicides and fungicides', 'Staré Město');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (495, 'X Viate', 'Toxic effect of formaldehyde', 'Amiens');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (496, 'Metoprolol Succinate', 'Stenosis due to nervous system prosth dev/grft, subs', 'Rungis');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (497, 'Ulta Vanilla Sugar Anti-Bacterial Hand Sanitizer', 'Toxic effect of carbon dioxide, assault, subs encntr', 'Carletonville');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (498, 'Undecylenic Acid', 'Segmental and somatic dysfunction of lower extremity', 'Skaramangás');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (499, 'Heparin Sodium', 'Laceration of popliteal vein, left leg, initial encounter', 'Nakhon Si Thammarat');
insert into TALELTOV.COMMUNITY (comid, comname, cdescription, city) values (500, 'OP-P', 'Disp fx of neck of scapula, l shldr, subs for fx w nonunion', 'Dongyu');
commit;




